### ISSUE TITLE
EntitySnapshot naming

### ISSUE THREAD

**Issue by delaneyj** [mayakwd/tick-knock#10]
It would be nice if the API was more explicit.  Maybe `snapshot.get()` should be `snapshot.previous` and `entity` be `current` ?  I hadn't read the docs thoroughly enough and got tripped up by it.

**Comment by mayakwd** [comment]
Thank you for the suggestions. I guess you're right.

**Comment by mayakwd** [comment]
Fixed in 3.0.0
