### ISSUE TITLE
onAddedToEngine/onRemovedFromEngine should be promise based

### ISSUE THREAD

**Issue by delaneyj** [mayakwd/tick-knock#11]
I have a situation where resource need to be loaded from external resource, it would clean it up a lot those to function where async

**Comment by mayakwd** [comment]
I know that it's a bit too late to answer this issue, but I can't just close it without any explanation.

ECS is designed to work synchronously and depends on processing data in a specific order. Adding asynchronous methods would go against this core principle.

A better approach might be to keep ECS focused on synchronous data processing. You could use tags or components to indicate when asynchronous operations are complete, signaling that it's safe to move forward.

For example:
```typescript
const {sharedConfig}= engine;
loadAssets({
  onStart: () => { sharedConfig.add(Tag.ASSETS_LOADING); },
  onComplete: () => { sharedConfig.remove(Tag.ASSETS_LOADING); }
});
```

Based on the presence of this tag, you can prevent some/all of your systems from processing.
```typescript SomeSystem
class SomeSystem extends System {
  public update(dt: number) {
    if (sharedConfig.has(Tag.ASSETS_LOADING) return;
    // ... 
  }
}
```
