### ISSUE TITLE
Adding component or tag to entity after a system has been added to the engine breaks the Entity tags

### ISSUE THREAD

**Issue by Maniae** [mayakwd/tick-knock#13]
Hello, thank you for this great library !

With this snippet : 

`class FakeSystem extends ReactionSystem {
	constructor() {
		super((entity) => {
			console.log("testing entity", entity.id, entity.has("FIRST"), entity.has(Velocity), entity.has("THIRD"));
			return true;
		});
	}
	update() {}
}

const myEntity = new Entity();
myEntity.addTag("FIRST");
const engine = new Engine();

engine.addSystem(new FakeSystem());
engine.addEntity(myEntity);
myEntity.add(new Velocity(0, 0));
myEntity.addTag("THIRD");`

We have this output : 

> testing entity 1 true false false
> testing entity 2 false true false
> testing entity 2 false true true

Adding a component or a tag after the system has been added to the engine somehow create a new fake Entity with a new id missing any existing Tags. Causing them to not been used in the system update function.

I don't see any workaround beside not using tags there ?

**Comment by mayakwd** [comment]
Hi, @Maniae, thank you for reporting the issue!

It's not quite like that as described. Actually, tags are still in your Entity, and you see how predicate works with helper entity, which content is being copied from the original Entity. 

But your report gave a clue, that I really have a bug in the matching process. Tags are not copied. I'll fix it in the next release. Thank you!.

**Comment by mayakwd** [comment]
Fixed in 3.0.0
