### ISSUE TITLE
Linked Components

### ISSUE THREAD

**Issue by dustinlacewell** [mayakwd/tick-knock#17]
I worry about the "Linked Component" design.

Currently, when you remove a component, tick-knock simply removes the entire component chain from the entity by deleting it from the mapping:

```ts
    const value = this._components[id];
    delete this._components[id];
```

This means you can't remove a specific instance of a linked component beyond just traversing the linked list and patching it up yourself. Is this really a useful design?

Why not simply have components _always_ internally managed as a list of instances of that component type. Then when you `get`, it returns the first instance. If you `getAll` you get the internally managed list.

`has` can similarly test there is at least one instance of the component type. `hasMany` could be introduced to determine if the entity has multiple instances of the same component.

`hasAll` could even be made particularly fancy in that you could wrap component types in an array to indicate you want to test for multiple instances: `e => e.hasAll(Health, [Damage])`. Whatever all the affected apis end up being, I'm finding that a linked-list implementation is not convenient.

**Comment by mayakwd** [comment]
Hey, @dustinlacewell!
They were introduced for only one reason - to have an option to get multiple instances of the same component at the time. 
I'll try to figure out how the API can become more convenient. 

If you have more suggestions or can help me design proper API, I will be grateful.

**Comment by dustinlacewell** [comment]
I also wanted to bring to your attention that I've created a project called React ECS that is based on tick-knock:

https://react-ecs.ldlework.com/

If you wanted to chat sometime, there's a link on the page to a Discord where we could discuss stuff :)

**Comment by mayakwd** [comment]
Hey!
Version 4.0.0 was released. Now, tick-tock supports linked components more conveniently. 

Check [CHANGELOG.md](https://github.com/mayakwd/tick-knock/blob/develop/CHANGELOG.md) and [How-To section](https://github.com/mayakwd/tick-knock#how-to-work-with-linked-components).
