### ISSUE TITLE
Release 4.0.1(?) containing ReactionSystem export in definitions file (index.d.ts)

### ISSUE THREAD

**Issue by SINePrime** [mayakwd/tick-knock#24]
Releases nor npm package are up to date with the source, which notably contains the ReactionSystem export included in index.d.ts.

**Comment by SINePrime** [comment]
Previously I had put in an issue #23 where I mistook `master` as 4.0.0, while the package remains out of date. I am putting this new issue in for the actual problem (outdated release and npm package).

**Comment by mayakwd** [comment]
Version 4.0.1 released.
