### ISSUE TITLE
It's not safe to remove current entity during iteration.

### ISSUE THREAD

**Issue by LouisSong** [mayakwd/tick-knock#46]
when use any built-in system as base class. It's not safe to remove current entity during iteration.

### example

*    if the HealthSystem's query matches 3 entities (Hero),theirs health are 1、100、100. in the update function, the first hero's health will be changed to 0, then removed from engine.the next hero will be the third one,not the second one.  i must add the i-- code. Can you provide a method to safely remove items during iteration?

``` typescript

  export class HealthSystem extends ReactionSystem {
   //...
    public update(dt: number): void {
        var entities:ReadonlyArray<Entity> = this.entities;
        for(var i=0;i<entities.length;i++){
            var entity = entities[i];
            const hero = entity.get(Hero);
            hero.helth--;
            if(hero.helth<=0){
                this.engine.removeEntity(entity);
                i--;   //this code is needed when remove entity during iteration.
            }
        }
   }
  //...
```

**Comment by mayakwd** [comment]
There are several options to perform what you are expecting:
1. You can iterate over entities backwards, starting from the last entity. This option removes the need to control index with the condition
```typescript
var i = entities.length
while (-- i >= 0) {
   const entity = entities[i];
   if (--hero.health <= 0) {
      this.engine.removeEntity(entity);
   }
}
```

2. You can create entities array copy, that will preserve your iteration ordering
```typescript
const entities = this.entities.concat()
for (entity of entities) {
   const hero = entity.get(Hero);
   hero.health--;
   if (hero.health <= 0){
     this.engine.removeEntity(entity);
   }
}
```

3. The common way to implement entities removal in ECS pattern is marking them with some tag/component indicating removal request and implementing system that processes such entities:
```typescript
const DEAD = "dead"

class HealthSystem extends ReactionSystem {
   public constructor() {
      super((entity) => entity.has(Health) && !entity.has(DEAD))
   }

   public update(dt: number): void {
      for (entity of entities) {
         const health = entity.get(Health)!
         if (--health.value<= 0) entity.add(DEAD)
      }
   }
}

class DeadRemovalSystem extends ReactionSystem {
   public constructor() {
        super((entity) => entity.has(DEAD));
   }
  
   public update(dt: number): void {
       while (this.entities.length > 0) {
          this.engine.removeEntity(this.entities[this.entities.length-1]);
       }
   }
}
```

Anyway, I've added a safe removal possibility, that will be available in the version 4.3.0.
```typescript
this.engine.removeEntityt(entity, true)
```
